theme: jekyll-theme-minimal
title: PaCE
logo: "/images/logo.png?raw=true" # your photo (or logo) here
navbar:    
  title: "Thomas Chadefaux"
  type: inverse
  left:
    - text: "Home"      
      href: http://chadefaux.github.io/
    - text: "Research"      
      href: http://chadefaux.github.io/research.html
    - text: "Teaching"      
      href: http://chadefaux.github.io/teaching.html
